In [20]:
# Gerekli kütüphanelerimizi tanımlıyoruz.
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
from sklearn.preprocessing import LabelEncoder
from sklearn.preprocessing import OneHotEncoder

In [21]:
# Veri setimizi yüklüyoruz.
veriler = pd.read_csv('ev-fiyat-verisi.csv')
veriler.head()

sehir  oda_sayisi  salon_sayisi  ev_yasi   fiyat
0  bursa           1             1        6  300000
1  bursa           2             1        4  400000
2  bursa           3             1        3  550000
3  bursa           4             1        5  750000
4  bursa           5             1       15  650000

In [22]:
# Verimiz içerisindeki numerik ve kategorik değerleri ayırıyoruz.
sehir = veriler.iloc[:,0:1].values # kategorik
numeric_veri = veriler.iloc[:,1:].values

numeric_veri

array([[      1,       1,       6,  300000],
       [      2,       1,       4,  400000],
       [      3,       1,       3,  550000],
       [      4,       1,       5,  750000],
       [      5,       1,      15,  650000],
       [      5,       2,      10,  675000],
       [      6,       1,       2, 1000000],
       [      6,       2,       6, 1050000],
       [      7,       1,       1, 1500000],
       [      1,       1,       5,  700000],
       [      2,       1,       7,  850000],
       [      3,       1,       2,  950000],
       [      4,       1,      10, 1050000],
       [      4,       1,      15, 1000000],
       [      5,       1,      12, 1350000],
       [      1,       1,       3,  500000],
       [      1,       1,       4,  475000],
       [      2,       1,       1,  750000],
       [      2,       1,       7,  700000],
       [      3,       1,       9,  875000],
       [      3,       1,      15,  850000],
       [      5,       2,      20, 1000000]], dtype=int

In [23]:
# Kategorik değer olan "şehir" değerine sırayla label ve one hot encoder uyguluyoruz.
le = LabelEncoder()
sehir[:,0] = le.fit_transform(sehir[:,0])


ohe = OneHotEncoder()
sehir=ohe.fit_transform(sehir).toarray()

sehir

array([[0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.]])

In [24]:
# Verimizi numpy dizisinden pandas dataframe'i haline getiriyoruz.
sehir_df = pd.DataFrame(data = sehir, index = range(22), columns=['ankara','bursa','istanbul'] )
numeric_veri_df =pd.DataFrame(data = numeric_veri, index = range(22), columns = ['oda_sayisi','salon_sayisi','ev_yasi','fiyat'])

#dataframe birlestirme islemi
veri_birlestirme=pd.concat([sehir_df,numeric_veri_df],axis=1)
veri_birlestirme

ankara  bursa  istanbul  oda_sayisi  salon_sayisi  ev_yasi    fiyat
0      0.0    1.0       0.0           1             1        6   300000
1      0.0    1.0       0.0           2             1        4   400000
2      0.0    1.0       0.0           3             1        3   550000
3      0.0    1.0       0.0           4             1        5   750000
4      0.0    1.0       0.0           5             1       15   650000
5      0.0    1.0       0.0           5             2       10   675000
6      0.0    1.0       0.0           6             1        2  1000000
7      0.0    1.0       0.0           6             2        6  1050000
8      0.0    1.0       0.0           7             1        1  1500000
9      0.0    0.0       1.0           1             1        5   700000
10     0.0    0.0       1.0           2             1        7   850000
11     0.0    0.0       1.0           3             1        2   950000
12     0.0    0.0       1.0           4             1       10  1050000
13     0.0    0.0       1.0           4             1       15  1000000
14     0.0    0.0       1.0           5             1       12  1350000
15     1.0    0.0       0.0           1             1        3   500000
16     1.0    0.0       0.0           1             1        4   475000
17     1.0    0.0       0.0           2             1        1   750000
18     1.0    0.0       0.0           2             1        7   700000
19     1.0    0.0       0.0           3             1        9   875000
20     1.0    0.0       0.0           3             1       15   850000
21     1.0    0.0       0.0           5             2       20  1000000

In [25]:
# Fiyat tahmini yapacağımız için kolonları ayırıyoruz.

x = veri_birlestirme.iloc[:,0:6].values
y = veri_birlestirme.iloc[:,6:].values
x

array([[ 0.,  1.,  0.,  1.,  1.,  6.],
       [ 0.,  1.,  0.,  2.,  1.,  4.],
       [ 0.,  1.,  0.,  3.,  1.,  3.],
       [ 0.,  1.,  0.,  4.,  1.,  5.],
       [ 0.,  1.,  0.,  5.,  1., 15.],
       [ 0.,  1.,  0.,  5.,  2., 10.],
       [ 0.,  1.,  0.,  6.,  1.,  2.],
       [ 0.,  1.,  0.,  6.,  2.,  6.],
       [ 0.,  1.,  0.,  7.,  1.,  1.],
       [ 0.,  0.,  1.,  1.,  1.,  5.],
       [ 0.,  0.,  1.,  2.,  1.,  7.],
       [ 0.,  0.,  1.,  3.,  1.,  2.],
       [ 0.,  0.,  1.,  4.,  1., 10.],
       [ 0.,  0.,  1.,  4.,  1., 15.],
       [ 0.,  0.,  1.,  5.,  1., 12.],
       [ 1.,  0.,  0.,  1.,  1.,  3.],
       [ 1.,  0.,  0.,  1.,  1.,  4.],
       [ 1.,  0.,  0.,  2.,  1.,  1.],
       [ 1.,  0.,  0.,  2.,  1.,  7.],
       [ 1.,  0.,  0.,  3.,  1.,  9.],
       [ 1.,  0.,  0.,  3.,  1., 15.],
       [ 1.,  0.,  0.,  5.,  2., 20.]])

In [26]:
# Lineer regresyyon kullanrak modelimizi oluşturuyouz.
from sklearn.model_selection import train_test_split
x_train, x_test,y_train,y_test = train_test_split(x,y,test_size=0.33, random_state=0)

from sklearn.linear_model import LinearRegression
regressor = LinearRegression()
regressor.fit(x_train,y_train)

y_pred = regressor.predict(x_test)

In [27]:
# Modelimize forward selection uygulamak için verilerimizi uygun hale getiriyoruz.
x = pd.DataFrame(data = x, index = range(22), columns=['ankara','bursa','istanbul','oda_sayisi','salon_sayisi','ev_yasi'] )
print(type(x)) # forward selecetion için dataframe yapısında olmalıdır
print(type(y)) # forward selecetion için numpy dizisi haline olmalıdır
x

<class 'pandas.core.frame.DataFrame'>
<class 'numpy.ndarray'>


ankara  bursa  istanbul  oda_sayisi  salon_sayisi  ev_yasi
0      0.0    1.0       0.0         1.0           1.0      6.0
1      0.0    1.0       0.0         2.0           1.0      4.0
2      0.0    1.0       0.0         3.0           1.0      3.0
3      0.0    1.0       0.0         4.0           1.0      5.0
4      0.0    1.0       0.0         5.0           1.0     15.0
5      0.0    1.0       0.0         5.0           2.0     10.0
6      0.0    1.0       0.0         6.0           1.0      2.0
7      0.0    1.0       0.0         6.0           2.0      6.0
8      0.0    1.0       0.0         7.0           1.0      1.0
9      0.0    0.0       1.0         1.0           1.0      5.0
10     0.0    0.0       1.0         2.0           1.0      7.0
11     0.0    0.0       1.0         3.0           1.0      2.0
12     0.0    0.0       1.0         4.0           1.0     10.0
13     0.0    0.0       1.0         4.0           1.0     15.0
14     0.0    0.0       1.0         5.0           1.0     12.0
15     1.0    0.0       0.0         1.0           1.0      3.0
16     1.0    0.0       0.0         1.0           1.0      4.0
17     1.0    0.0       0.0         2.0           1.0      1.0
18     1.0    0.0       0.0         2.0           1.0      7.0
19     1.0    0.0       0.0         3.0           1.0      9.0
20     1.0    0.0       0.0         3.0           1.0     15.0
21     1.0    0.0       0.0         5.0           2.0     20.0

In [28]:
# Forward Selection işlemimizi başlatıyoruz.
import statsmodels.api as sm
X=np.append(arr=np.ones((22,1)).astype(int), values=x, axis=1)
X_opt=x.iloc[:,[0,1,2,3,4,5]].values


regressor_OLS = sm.OLS(endog = y, exog = X_opt).fit()
print(regressor_OLS.summary())

                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.923
Model:                            OLS   Adj. R-squared:                  0.899
Method:                 Least Squares   F-statistic:                     38.33
Date:                Thu, 20 Oct 2022   Prob (F-statistic):           2.36e-08
Time:                        19:52:45   Log-Likelihood:                -279.41
No. Observations:                  22   AIC:                             570.8
Df Residuals:                      16   BIC:                             577.4
Df Model:                           5                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1          5.091e+05    7.7e+04      6.609      0.0

In [29]:
# x1,x3 ve x4 değerleri aynı olan en düşük p value değerleri olduğundan hesaplamaya beraber eklenmektedir.
X=np.append(arr=np.ones((22,1)).astype(int), values=x, axis=1)
X_opt=x.iloc[:,[0,2,3]].values


regressor_OLS = sm.OLS(endog = y, exog = X_opt).fit()
print(regressor_OLS.summary())

                                 OLS Regression Results                                
Dep. Variable:                      y   R-squared (uncentered):                   0.983
Model:                            OLS   Adj. R-squared (uncentered):              0.981
Method:                 Least Squares   F-statistic:                              375.8
Date:                Thu, 20 Oct 2022   Prob (F-statistic):                    4.35e-17
Time:                        19:52:45   Log-Likelihood:                         -286.83
No. Observations:                  22   AIC:                                      579.7
Df Residuals:                      19   BIC:                                      582.9
Df Model:                           3                                                  
Covariance Type:            nonrobust                                                  
                 coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------

In [30]:
# p value değerleri halen 0.05'ten küçük olduğundan bir sonraki en küçük p value değeri olan x6 sisteme eklenir.
X=np.append(arr=np.ones((22,1)).astype(int), values=x, axis=1)
X_opt=x.iloc[:,[0,2,3,5]].values


regressor_OLS = sm.OLS(endog = y, exog = X_opt).fit()
print(regressor_OLS.summary())


                                 OLS Regression Results                                
Dep. Variable:                      y   R-squared (uncentered):                   0.990
Model:                            OLS   Adj. R-squared (uncentered):              0.987
Method:                 Least Squares   F-statistic:                              426.4
Date:                Thu, 20 Oct 2022   Prob (F-statistic):                    1.46e-17
Time:                        19:52:46   Log-Likelihood:                         -281.75
No. Observations:                  22   AIC:                                      571.5
Df Residuals:                      18   BIC:                                      575.9
Df Model:                           4                                                  
Covariance Type:            nonrobust                                                  
                 coef    std err          t      P>|t|      [0.025      0.975]
-----------------------------------------

In [31]:
# p value değerleri halen 0.05'ten küçük olduğundan bir sonraki en küçük p value değeri olan x2 sisteme eklenir.
X=np.append(arr=np.ones((22,1)).astype(int), values=x, axis=1)
X_opt=x.iloc[:,[0,1,2,3,5]].values


regressor_OLS = sm.OLS(endog = y, exog = X_opt).fit()
print(regressor_OLS.summary())


                            OLS Regression Results                            
Dep. Variable:                      y   R-squared:                       0.915
Model:                            OLS   Adj. R-squared:                  0.895
Method:                 Least Squares   F-statistic:                     45.91
Date:                Thu, 20 Oct 2022   Prob (F-statistic):           6.79e-09
Time:                        19:52:46   Log-Likelihood:                -280.45
No. Observations:                  22   AIC:                             570.9
Df Residuals:                      17   BIC:                             576.4
Df Model:                           4                                         
Covariance Type:            nonrobust                                         
                 coef    std err          t      P>|t|      [0.025      0.975]
------------------------------------------------------------------------------
x1          4.372e+05   5.27e+04      8.289      0.0

In [32]:
# Son eklenen 1. index değerinden sonra p value değeri 0.05'i geçtiğinden dolayı 1.index sisteme eklenmemelidir.
# 1. index haricinde eklenmiş ve p value değeri 0.05'in altında olan 0,2,3,5 index değerleri ile model eğitimi gerçekleştirilmektedir.
x_train, x_test,y_train,y_test = train_test_split(x.iloc[:,[0,2,3,5]],y,test_size=0.33, random_state=0)

regressor = LinearRegression()
regressor.fit(x_train,y_train)

y_pred = regressor.predict(x_test)